import { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ChevronRight, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Form } from "@/components/ui/form";
import { useCart } from "@/hooks/useCart";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import { CheckoutContactForm } from "@/components/checkout/CheckoutContactForm";
import { CheckoutDeliveryForm } from "@/components/checkout/CheckoutDeliveryForm";
import { CheckoutPaymentForm } from "@/components/checkout/CheckoutPaymentForm";
import { CheckoutOrderSummary } from "@/components/checkout/CheckoutOrderSummary";

const checkoutSchema = z.object({
  firstName: z.string().min(2, "Мінімум 2 символи").max(100, "Максимум 100 символів"),
  lastName: z.string().min(2, "Мінімум 2 символи").max(100, "Максимум 100 символів"),
  email: z.string().email("Невірний формат email"),
  phone: z.string().min(10, "Введіть коректний номер телефону").max(20, "Максимум 20 символів"),
  deliveryMethod: z.enum(["pickup", "nova_poshta", "courier"], {
    required_error: "Оберіть спосіб доставки",
  }),
  deliveryCity: z.string().optional(),
  deliveryAddress: z.string().optional(),
  paymentMethod: z.enum(["cash", "online"], {
    required_error: "Оберіть спосіб оплати",
  }),
  notes: z.string().optional(),
}).refine(
  (data) => {
    if (data.deliveryMethod === "nova_poshta" || data.deliveryMethod === "courier") {
      return !!data.deliveryCity && data.deliveryCity.length >= 2;
    }
    return true;
  },
  {
    message: "Вкажіть місто доставки",
    path: ["deliveryCity"],
  }
).refine(
  (data) => {
    if (data.deliveryMethod === "nova_poshta" || data.deliveryMethod === "courier") {
      return !!data.deliveryAddress && data.deliveryAddress.length >= 2;
    }
    return true;
  },
  {
    message: "Вкажіть адресу доставки",
    path: ["deliveryAddress"],
  }
);

type CheckoutFormData = z.infer<typeof checkoutSchema>;

export default function Checkout() {
  const navigate = useNavigate();
  const { items, totalPrice, clearCart } = useCart();
  const { user } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<CheckoutFormData>({
    resolver: zodResolver(checkoutSchema),
    defaultValues: {
      firstName: "",
      lastName: "",
      email: "",
      phone: "",
      deliveryMethod: "pickup",
      deliveryCity: "",
      deliveryAddress: "",
      paymentMethod: "cash",
      notes: "",
    },
  });

  // Autofill for logged-in users
  useEffect(() => {
    async function loadProfile() {
      if (!user) return;

      const { data: profile } = await supabase
        .from("profiles")
        .select("first_name, last_name, email, phone")
        .eq("user_id", user.id)
        .single();

      if (profile) {
        form.setValue("firstName", profile.first_name || "");
        form.setValue("lastName", profile.last_name || "");
        form.setValue("email", profile.email || user.email || "");
        form.setValue("phone", profile.phone || "");
      } else if (user.email) {
        form.setValue("email", user.email);
      }
    }

    loadProfile();
  }, [user, form]);

  // Redirect if cart is empty
  useEffect(() => {
    if (items.length === 0) {
      navigate("/cart");
    }
  }, [items, navigate]);

  const onSubmit = async (data: CheckoutFormData) => {
    if (items.length === 0) {
      toast({
        title: "Кошик порожній",
        description: "Додайте товари в кошик перед оформленням",
        variant: "destructive",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      // Get default status
      const { data: defaultStatus } = await supabase
        .from("order_statuses")
        .select("id")
        .eq("is_default", true)
        .single();

      // Create order
      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert({
          user_id: user?.id || null,
          first_name: data.firstName,
          last_name: data.lastName,
          email: data.email,
          phone: data.phone,
          delivery_method: data.deliveryMethod,
          delivery_city: data.deliveryCity || null,
          delivery_address: data.deliveryAddress || null,
          payment_method: data.paymentMethod,
          notes: data.notes || null,
          status_id: defaultStatus?.id || null,
          subtotal: totalPrice,
          total: totalPrice,
          order_number: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map((item) => ({
        order_id: order.id,
        product_id: item.productId,
        modification_id: item.modificationId || null,
        name: item.modificationName
          ? `${item.name} - ${item.modificationName}`
          : item.name,
        price: item.price,
        quantity: item.quantity,
        total: item.price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from("order_items")
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Clear cart and redirect
      clearCart();
      
      toast({
        title: "Замовлення оформлено!",
        description: `Номер замовлення: ${order.order_number}`,
      });

      // Navigate to success page
      if (user) {
        navigate(`/order-success/${order.id}`);
      } else {
        navigate(`/order-success/${order.id}?token=${order.access_token}`);
      }
    } catch (error: any) {
      console.error("Order creation error:", error);
      toast({
        title: "Помилка оформлення",
        description: error.message || "Спробуйте ще раз",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (items.length === 0) {
    return null;
  }

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Breadcrumbs */}
      <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-6">
        <Link to="/" className="hover:text-foreground transition-colors">
          Головна
        </Link>
        <ChevronRight className="h-4 w-4" />
        <Link to="/cart" className="hover:text-foreground transition-colors">
          Кошик
        </Link>
        <ChevronRight className="h-4 w-4" />
        <span className="text-foreground">Оформлення замовлення</span>
      </nav>

      <div className="flex items-center gap-4 mb-8">
        <Button variant="ghost" size="icon" asChild>
          <Link to="/cart">
            <ArrowLeft className="h-5 w-5" />
          </Link>
        </Button>
        <h1 className="text-3xl font-bold">Оформлення замовлення</h1>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)}>
          <div className="grid lg:grid-cols-3 gap-8">
            {/* Forms column */}
            <div className="lg:col-span-2 space-y-6">
              <CheckoutContactForm form={form} />
              <CheckoutDeliveryForm form={form} />
              <CheckoutPaymentForm form={form} />
            </div>

            {/* Order summary column */}
            <div className="lg:col-span-1">
              <CheckoutOrderSummary
                items={items}
                totalPrice={totalPrice}
                form={form}
                isSubmitting={isSubmitting}
              />
            </div>
          </div>
        </form>
      </Form>
    </div>
  );
}
